Vagrant.configure("2") do |config|
  config.vm.define "devchain-vm"
  config.vm.box = "ubuntu/xenial64"

  config.vm.network :private_network, ip: "192.168.3.3"
  config.vm.network "forwarded_port", guest: 8080, host: 10080

  config.vm.synced_folder "shared", "/home/ubuntu/shared", nfs: true, nfs_udp: false, create: true

  config.vm.provider "virtualbox" do |v|
    v.name = "truffle-vm"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  #For Linux and MacOS user
  #config.vm.synced_folder "shared", "/home/ubuntu/shared",
  #type: "rsync",
  #rsync__exclude: ".git/",
  #rsync__auto: "true"
end
