# Copyright 2017 - Dechain User Group

# coding: utf-8
Vagrant.configure("2") do |config|
  config.vm.define "devchain-vm"
  config.vm.box = "ubuntu/xenial64"

  config.vm.network :private_network, ip: "192.168.3.3"
  config.vm.network "forwarded_port", guest: 8080, host: 10080, host_ip: "127.0.0.1", auto_correct: true
  config.vm.network "forwarded_port", guest: 10000, host: 10000, protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10001, host: 10001, protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10002, host: 10002, protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10003, host: 10003, protocol: "tcp", auto_correct: true

  config.vm.network "forwarded_port", guest: 10000, host: 10000, protocol: "udp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10001, host: 10001, protocol: "udp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10002, host: 10002, protocol: "udp", auto_correct: true
  config.vm.network "forwarded_port", guest: 10003, host: 10003, protocol: "udp", auto_correct: true


  config.vm.synced_folder "../..", "/home/ubuntu/share"

  config.vm.provider "virtualbox" do |v|
    v.name = "devchain-vm"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  #For Linux and MacOS user
  #config.vm.synced_folder "shared", "/home/ubuntu/shared",
  #type: "rsync",
  #rsync__exclude: ".git/",
  #rsync__auto: "true"
end
