#!/bin/sh
exec 2>&1
export NODE_ENV="production"
export RPC_HOST="localhost"
export RPC_PORT="10001"
export LISTENING_PORT="10003"
export WS_SERVER="wss://factory.shinit.net:15000"
export WS_SECRET="20170420devchain"  # see http://forum.ethereum.org/discussion/2112/how-to-add-yourself-to-the-stats-dashboard-its-not-automatic
export VERBOSITY=2

exec su -c "node /home/eth/eth-net-intelligence-api/app.js" eth
