version: '2'
services:
  geth-devchain:
    container_name: geth-devchain
    build: ./geth
    environment:
      - NETWORKID=2017042099
      - MINERTHREADS=1
    volumes:
      - ../eth-data:/eth-data
    ports:
      - "10001:8545"  # rpc
      - "10002:8546"  # websockets
      - "10003:30303"

  geth-dev:
    image: ethereum/client-go:v1.7.2
    command: ["--datadir", "/root/.ethereum", "--nodiscover", "--maxpeers", "0", "--networkid", "1337",
      "--rpc", "--rpcaddr", "0.0.0.0", "--rpccorsdomain", "*", "--ws", "--wsaddr", "0.0.0.0", "--wsorigins", "*", "--unlock", "0,1,2", "--password", "/root/.ethereum/coinbase_pwd.txt",
      "--mine", "--minerthreads", "1", "--dev"]
    volumes:
      - ./eth-data-dev:/root/.ethereum
      - ./keystore:/root/.ethereum/keystore
    expose: ["8546"]
    ports: ["8545:8545", "8546:8546"]


  # docker run -it --net=host --entrypoint bash docker_ethnetintel-devchain
  ethnetintel-devchain:
    container_name: ethnetintel-devchain
    build: ./ethnetintel
    volumes:
      - ../projects:/projects
    links:
      - geth-devchain

  eth-polygon:
    container_name: eth-polygon
    build: ./eth-polygon
    volumes:
      - ../projects:/projects
    ports:
      - "8544:8545"
    links:
      - geth-devchain
    user: node
